import React from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import Questionnaire from '../components/questionnaire';
import Footer from '../components/footer';

const dashboard = () => {
    return (
        <>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar/>
            <div className='px-8 text-center'>
                <h1 className='sm:text-left sm:pl-4 pl-0 text-center text-3xl pt-8 pb-14'>Mes questionnaires</h1>
                <div className='flex flex-wrap justify-center sm:justify-between'>
                    <Questionnaire/>
                    <Questionnaire/>
                    <Questionnaire/>
                </div>
            </div>
            <Footer/>
        </>
    );
};

export default dashboard;