import React from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import Questionnaire from '../components/questionnaire';
import Footer from '../components/footer';

const dashboard = () => {
    return (
        <>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar/>
                <h1 className='text-2xl px-4 py-8'>Mes questionnaires</h1>
            <Questionnaire/>
            <Footer/>
        </>
    );
};

export default dashboard;