import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import clientPromise from '../lib/mongodb'
import { useEffect, useState } from 'react'

export default function Home({isConnected}) {
  const [restaurants, setRestaurants] = useState([]);

  useEffect(() => {
    (async () => {
      const results = await fetch('/api/list');
      const resultsJson = await results.json();
      setRestaurants(resultsJson);
    })();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {restaurants.map((restaurant) => (
            <div className='card' key={restaurant.id}>
              <h2>{restaurant.name}</h2>
              <p>{restaurant.cuisine}</p>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context) {
  try{
    await clientPromise
    return {
      props: { isConnected: true },
    }
  } catch (e) {
    console.error(e);
    return {
      props: { isConnected: false },
    }
  }
}
