import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Accueil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>

        <figure>
          <Image src="/image/logo.png" width={300} height={300} alt="Logo" />
        </figure>
        <h1>Code pin</h1>

        <form>
          <input type="text" placeholder='Code de la session'></input>
          <input type="text" placeholder='Prénom'></input>
          <button type="submit">Rejoindre la session</button>
        </form>
      </main>
    </div>
  )
}