import React from 'react'
import Image from 'next/image'
import Head from 'next/head'

const signup = () => {
  return (
    <div>
      <Head>
        <title>S'inscrire</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='text-center'>
        <figure>
          <Image src="/image/logo.png" width={250} height={250} alt="Logo" className="mx-auto"/>
        </figure>
        <h1 className='font-bold text-3xl mb-12'>S'inscrire</h1>

        <form className='inline-grid w-9/12'>
          <input type="text" placeholder='Nom' className='mb-8 border-b-2 w-full'></input>
          <input type="text" placeholder='Prénom' className='mb-8 border-b-2 w-full'></input>
          <input type="text" placeholder='Adresse email' className='mb-8 border-b-2 w-full'></input>
          <input type="text" placeholder='Mot de passe' className='mb-12 border-b-2 w-full'></input>
          <button type="submit" className="bg-cyan-500 p-3 rounded-full text-white font-bold">S'inscrire</button>


          <div className="my-4 border-b border-black text-center">
              <div
                className="leading-none px-2 inline-block text-sm text-black tracking-wide font-medium bg-white transform translate-y-1/2"
              >
                Or sign up with Google
              </div>
            </div>



          <button type="submit" className="border-solid border-2 border-black mb-4 p-3 rounded-full  font-bold">S'inscrire avec Google</button>
        </form>

      </main>
    </div>
  );
};

export default signup;