import React from 'react'
import Image from 'next/image'
import Head from 'next/head'
import Link from 'next/link'
import { useState, useEffect } from 'react';
import toast from 'react-hot-toast';
import { useCookies } from 'react-cookie';
import { useRouter } from 'next/router';

export default function Signin() {

  const [inputedUser, setInputedUser] = useState({
    email: '',
    password: ''
  });
  const router = useRouter();
  const [cookies, setCookie, removeCookie] = useCookies();
  const [showPassword, setShowPassword] = useState(false);

  const handleConnectUser = async e => {
    e.preventDefault();
    try {
      toast.loading('Connexion en cours...');
      if (
        !inputedUser.email ||
        !inputedUser.email.includes('@') ||
        !inputedUser.password
      ) {
        toast.remove();
        toast.error('Informations incorrectes');
      } else {
        //POST form values
        const res = await fetch('/api/signin', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            email: inputedUser.email,
            password: inputedUser.password
          })
        });

        const data = await res.json();

        if (res.ok) {
          setCookie('user', JSON.stringify(data), {
            path: '/',
            maxAge: 2592000,
            sameSite: true,
            secure: true
          });
          toast.remove();
          toast.success('Connecté');
          router.push('/');
        } else {
          toast.remove();
          toast.error('Erreur lors de la connexion au compte');
        }
      }
    } catch (error) {
      console.log(error);
    }
  };
  useEffect(() => {
    if (cookies.user) {
      router.push('/');
    }
  }, [cookies.user, router]);

  return (
    <div>
      <Head>
        <title>Se connecter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-center">
      <main className='text-center w-full sm:w-1/2 lg:w-1/3'>
        <figure>
          <Image src="/image/logo.png" width={250} height={250} alt="Logo" className="mx-auto"/>
        </figure>
        <h1 className='font-bold text-3xl mb-12'>Se connecter</h1>

        <form method='POST' onSubmit={handleConnectUser} className='inline-grid w-9/12'>
          <input 
            type="text"
            placeholder='Adresse email'
            className='mb-8 border-b-2 w-full'
            value={inputedUser.email || ''}
            onChange={e =>
              setInputedUser({ ...inputedUser, email: e.target.value })
            }
          >
          </input>
          <div>
            <input 
              type={`${showPassword ? 'text' : 'password'}`}
              placeholder='Mot de passe' 
              className='mb-12 border-b-2 w-full'
              value={inputedUser.password || ''}
              minLength={8}
              onChange={e =>
                setInputedUser({
                  ...inputedUser,
                  password: e.target.value
                })
              }
            >
            </input>
            <div className="toggle">
              <input
                className="toggle-state"
                type="checkbox"
                name="check"
                value="check"
                onClick={() => setShowPassword(!showPassword)}
              />
              <div className="indicator"></div>
            </div>
          </div>
          
          <button type="submit" className="bg-cyan-500 p-3 rounded-full text-white font-bold mb-2">Se connecter</button>
          <p className='text-sm ml-2 hover:text-cyan-500 cursor-pointer mb-12'>Mot de passe oublié ?</p>


          <button type="submit" className="border-solid border-2 border-cyan-500 text-cyan-500 p-3 rounded-full  font-bold">Connexion avec Google</button>

          <div className="my-4 border-b border-black text-center">
              <div
                className="leading-none px-2 inline-block text-sm text-black tracking-wide font-medium bg-white transform translate-y-1/2"
              >
                Ou s'inscrire
              </div>
          </div>


          
            <button type="submit" className="border-solid border-2 border-black mb-4 p-3 rounded-full  font-bold"><Link href="/signup">S'inscrire</Link></button>
          
        </form>

      </main>
      </div>
    </div>
  );
};